# Site settings
title: Katy Bowman | Writer
email: k80@katybowman.com
description: > # this means to ignore newlines until "baseurl:"
  Katy Bowman writing profile.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://katybowman.com" # the base hostname & protocol for your site
twitter_username: k80bowman
github_username:  k80bowman

# Build settings
markdown: kramdown
